### PR TITLE
Scikit-learn library + LNC

### PR DESCRIPTION
**Pull request by GuidoBallabio**
I've adapted your library to work with the algorithms for knn from the scikit-learn library. Also a minor increase in performance should be expected.
I've also added the LNC term in MI as an option (as default alpha=0 makes it disappear).
The implementation of LNC is a modern rewriting of the homonymous repo you pointed to in your README and tested against it for correctness (from the paper I found your are one of the authors as well).
I did it for my own use but I leave it here just I case, it could help someone if you want to merge.

P.S. I'm not sure about how to implement LNC for CMI but so I made it just for MI, if you know how to add support for CMI I'd like to know thanks

Thank you for your work. If you need anything or just part of the modifications just ask and I'll make a cleaner pull request.

### CODE REVIEW

**Comment by gregversteeg** [comment]
This is fantastic, thank you! I just want a chance to review before merging, hopefully next week. Thanks again.

**Comment by gregversteeg** [comment]
This all looks great, thanks again for these contributions!

**Comment by dizcza** [comment]
@GuidoBallabio the list of `alpha` values should be taken according to the .xlsx file in the "homonymous" repo you refer to?

**Comment by GuidoBallabio** [comment]
@dizcza Yes, minding the dimensions and k that you chose.
However I improved the merged estimator and added an algorithm for alpha estimation in my fork, if you want to have a look at it. When I've time I'll do a pull request for that as well.

**Pull request merged**
